CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{

    public class WriterController : Controller
    {
     
        public IActionResult FotoGor()
        {


            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WriterLogin()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Test()
        {
            return View();

        }
    
        public PartialViewResult WriterFooter()
        {
            return PartialView();
        }
        [HttpGet]
   
        public async Task<IActionResult> EditProfile()
        {
            //IDENTITY LANINA GORE CALISIR DURUMDA GUNCEL

            //İLK YOL 


            //Context context = new Context();
            //UserManager userManager = new UserManager(new EfUserDal());
            //var username = User.Identity.Name;
            //var usermail = context.Users.Where(p => p.UserName == username).Select(k => k.Email).FirstOrDefault();
            //var id = context.Users.Where(p => p.Email == usermail).Select(k => k.Id).FirstOrDefault();
            //var values = userManager.GetById(id);
            //return View(values);


            //İLK YOL 


           


            return View();



        }
        [HttpPost]
        
        public  async Task<IActionResult> EditProfile(AppUser appUser)
        {

         
           
            //values.PasswordHash = _userManager.PasswordHasher.HashPassword(values, appUser.PasswordHash);
            //password change
         
            return RedirectToAction("Index","Dashboard");
           
            
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult AddWriter()
        {

            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public IActionResult AddWriter(AddProfileImage addProfileImage)
        {

        
            return View();
        }
    }
}

CoreDemo/Views/Writer/AddWriter.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "AddWriter";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<form class=" form-group" method="post" enctype="multipart/form-data">
    @using (Html.BeginForm("EditProfile", "Writer", FormMethod.Post))
    {
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Profili Düzenle</h4>
                    @*<p class="card-description"> Basic form elements </p>*@
                    <br />
                    @Html.HiddenFor(p => p.Id, new { @class = "form-control" })
                    <div class="forms-sample">
                        <div class="form-group">
                            <label for="exampleInputName1">Name</label>
                            <input type="text" class="form-control" id="exampleInputName1" name="WriterName" placeholder="Name">
                            @*@Html.TextBoxFor(p => p.WriterName, new { @class = "form-control" })*@

                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Email address</label>
                            <input type="email" class="form-control" id="exampleInputEmail3" name="WriterMail" placeholder="Email">
                            @*@Html.TextBoxFor(p => p.WriterMail, new { @class = "form-control" })*@
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword4" name="WriterPassword" placeholder="Password">
                            @*@Html.TextBoxFor(p => p.WriterPassword, new { @class = "form-control" })*@
                        </div>

                        <div class="form-group">
                            <label for="exampleInputCity1">Fotoğraf Yolu</label>
                            <input type="file" class="form-control" name="WriterImage" />
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

    }


</form>

CoreDemo/Views/Writer/EditProfile.cshtml
 @model EntityLayer.Concrete.AppUser

@{
    ViewData["Title"] = "EditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
@using (Html.BeginForm("EditProfile", "Writer", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Profili Düzenle</h4>
                @*<p class="card-description"> Basic form elements </p>*@
                <br />
                @Html.HiddenFor(p=>p.Id ,new {@class="form-control" })
                <form class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">Ad Soyad</label>
                        @*<input type="text" class="form-control" id="exampleInputName1" name="NameSurname" placeholder="Name">*@
                        @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })

                    </div>
                    <div class="form-group">
                        <label for="exampleInputName2"> Kullanıcı Adı </label>
                        <input type="text" name="UserName" class="form-control" placeholder="Kullanıcı Adı" />

                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Email address</label>
                        @*<input type="email" class="form-control" id="exampleInputEmail3" name="Email" placeholder="Email">*@
                        @Html.TextBoxFor(p => p.Email, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Password</label>
                        @*<input type="password" class="form-control" id="exampleInputPassword4" name="WriterPassword" placeholder="Password">*@
                        @Html.PasswordFor(p => p.PasswordHash, new { @class = "form-control" })
                    </div>
                  
                    <div class="form-group">
                        <label for="exampleInputCity1">Fotoğraf Yolu</label>
                        <input type="text" class="form-control" id="exampleInputCity1" name="WriterImage" placeholder="Location">
                    </div>
                  
                    <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>

}

CoreDemo/Views/Writer/FotoGor.cshtml
@using EntityLayer.Concrete
@model List<Writer>

@{
    ViewData["Title"] = "FotoGor";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Ad</th> 
       
       
        <th>Düzenle</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.WriterName</td>
            <td> <img src="~/WriterImageFiles/@item.WriterImage"  /></td>
         
        </tr>
    }

</table>

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

Another Love

CoreDemo/Views/Writer/WriterFooter.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm hakları saklıdır @DateTime.Now.Year</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.instagram.com/" target="_blank">Bootstrap admin templates </a> from Bootstrapdash.com</span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>


Login

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/WriterTheme/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">@User.Identity.Name</span>
                    <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../index.html">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        @*<li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Basic UI Elements</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-crosshairs-gps menu-icon"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="../../pages/ui-features/buttons.html">Buttons</a></li>
                    <li class="nav-item"> <a class="nav-link" href="../../pages/ui-features/typography.html">Typography</a></li>
                </ul>
            </div>
        </li>*@
        <li class="nav-item">
            <a class="nav-link" href="../../pages/icons/mdi.html">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Bloglarım">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/Inbox">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="../../pages/tables/basic-table.html">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message-alert menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">
                <span class="menu-title">Siteye Git</span>
                @*<i class="menu-arrow"></i>*@
                <i class="mdi mdi-car menu-icon"></i>
            </a>
            @*<div class="collapse" id="general-pages">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="../../pages/samples/blank-page.html"> Blank Page </a></li>
                    <li class="nav-item"> <a class="nav-link" href="../../pages/samples/login.html"> Login </a></li>
                    <li class="nav-item"> <a class="nav-link" href="../../pages/samples/register.html"> Register </a></li>
                    <li class="nav-item"> <a class="nav-link" href="../../pages/samples/error-404.html"> 404 </a></li>
                    <li class="nav-item"> <a class="nav-link" href="../../pages/samples/error-500.html"> 500 </a></li>
                </ul>
            </div>*@
        </li>
        @*<li class="nav-item sidebar-actions">
            <span class="nav-link">
                <div class="border-bottom">
                    <h6 class="font-weight-normal mb-3">Projects</h6>
                </div>
                <button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>
                <div class="mt-4">
                    <div class="border-bottom">
                        <p class="text-secondary">Categories</p>
                    </div>
                    <ul class="gradient-bullet-list mt-4">
                        <li>Free</li>
                        <li>Pro</li>
                    </ul>
                </div>
            </span>
        </li>*@
        <li class="nav-item">
            <a class="nav-link" href="../../pages/tables/basic-table.html">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Login/LogOut">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout menu-icon"></i>
            </a>
        </li>

    </ul>
</nav>